---
- hosts: all
  sudo: true
  vars:
      document_root: /vagrant
  #pre_tasks:
  #    - name: Update all yum packages
  #      yum: name=* state=latest
  tasks:
      - name: Install some required yum packages
        yum: name={{ item }} state=present
        with_items: 
          - python-psycopg2
          - libselinux-python
          - nano
          - vim
      - name: Install Postgres via yum
        yum: name={{ item }} state=present
        with_items:
          - postgresql
          - postgresql-server
          - postgresql-odbc
      - name: Initialize PostgreSQL database
        command: service postgresql initdb
                 creates=/var/lib/pgsql/data/postgresql.conf
      - name: Start PostgreSQL database service and enable on startup
        service: name=postgresql
                 state=started
                 enabled=yes
      - name: Enable normal login in PostgreSQL (1/3)
        lineinfile:
            dest=/var/lib/pgsql/data/pg_hba.conf
            regexp=^local(.*)ident$
            state=present
            backrefs=yes
            line='local\1trust'
            backup=yes
      - name: Enable normal login in PostgreSQL (2/3)
        lineinfile:
            dest=/var/lib/pgsql/data/pg_hba.conf
            regexp=^host(.*)ident$
            state=present
            backrefs=yes
            line='host\1trust'
            backup=yes
      - name: Enable normal login in PostgreSQL (3/3)
        lineinfile:
            dest=/var/lib/pgsql/data/pg_hba.conf
            regexp=^host(.*)ident$
            state=present
            backrefs=yes
            line='host\1trust'
            backup=yes
      - name: Restart PostgreSQL
        service: name=postgresql state=restarted
      - name: Create iRODS database
        postgresql_db:
            name=ICAT
      - name: Create PostgreSQL user and associate with db
        postgresql_user: db=ICAT name=irods password=hemligt
      - name: Give user irods privileges to ICAT database
        postgresql_privs:
            database=ICAT
            state=present
            privs=ALL
            type=database
            obj=ICAT
            role=irods
        postgresql_privs:
            database=ICAT
            state=present
            privs=ALL
            type=table
            objs=ALL_IN_SCHEMA
            schema=public
            roles=irods
        postgresql_privs:
            database=ICAT
            state=present
            privs=ALL
            type=sequence
            objs=ALL_IN_SCHEMA
            schema=public
            roles=irods
      - name: Download iRODS ICAT server package
        get_url:
            url=ftp://ftp.renci.org/pub/irods/releases/4.0.3/irods-icat-4.0.3-64bit-centos6.rpm
            dest=/vagrant/rpm/irods-icat-4.0.3-64bit-centos6.rpm
      - name: Download iRODS database plugins
        get_url:
            url=ftp://ftp.renci.org/pub/irods/releases/4.0.3-with-v1.4-database-plugins/irods-database-plugin-postgres-1.4-centos6.rpm
            dest=/vagrant/rpm/irods-database-plugin-postgres-1.4-centos6.rpm
      - name: Install iRODS ICAT server package
        yum:
            name=/vagrant/rpm/irods-icat-4.0.3-64bit-centos6.rpm
            state=present
      - name: Install iRODS database plugins
        yum:
            name=/vagrant/rpm/irods-database-plugin-postgres-1.4-centos6.rpm
            state=present
      - name: Generate password for iRODS user
        shell: openssl rand -base64 16 | sed 's,/,S,g' | cut -c 1-16 > /tmp/irodspass
        args:
          creates: /tmp/irodspass
      - name: Generate password for DB user
        shell: openssl rand -base64 16 | sed 's,/,S,g' | cut -c 1-16 > /tmp/dbpass
        args:
          creates: /tmp/dbpass
      - name: Generate responsefile
        command: /vagrant/scripts/generate_responsefile.sh /tmp/responses
        args:
          creates: /tmp/responses
      - name: Run iRODS configuration script
        shell: /var/lib/irods/packaging/setup_irods.sh < /tmp/responses
        args:
           creates: /etc/irods/service_account.config
      - name: Generate responses for iinit
        command: /vagrant/scripts/generate_iinitresponses.sh /tmp/iinitresponses
        args:
          creates: /tmp/iinitresponses
      - name: Running iinit for vagrant user
        shell: su vagrant -c 'iinit' < /tmp/iinitresponses
        args:
          creates: /home/vagrant/.irods/irodsEnv
