---
- hosts: all
  sudo: true
  vars:
      document_root: /vagrant
  pre_tasks:
      - name: Update all yum packages
        yum: name=* state=latest
  tasks:
      - name: Install some required yum packages
        yum: name={{ item }} state=present
        with_items: 
          - python-psycopg2
          - libselinux-python
          - nano
          - vim
      - name: Install Postgres via yum
        yum: name={{ item }} state=present
        with_items:
          - postgresql
          - postgresql-server
          - postgresql-odbc
      - name: Initialize PostgreSQL database
        command: service postgresql initdb
                 creates=/var/lib/pgsql/data/postgresql.conf
      - name: Start PostgreSQL database service and enable on startup
        service: name=postgresql
                 state=started
                 enabled=yes
      - name: Enable normal login in PostgreSQL
        lineinfile:
            dest=/var/lib/pgsql/data/pg_hba.conf
            regexp=local.*all.*all.*ident
            state=present
            line='local   all         all                               trust'
      - name: Restart PostgreSQL
        service: name=postgresql state=restarted
      - name: Create iRODS database
        postgresql_db:
            name=ICAT
      - name: Create PostgreSQL user and associate with db
        postgresql_user: db=ICAT name=irods password=hemligt
      - name: Give user irods privileges to ICAT database
        postgresql_privs:
            database=ICAT
            state=present
            privs=ALL
            type=database
            obj=ICAT
            role=irods
      #- name: Download iRODS RPM:s
        # ftp://ftp.renci.org/pub/irods/releases/4.0.3/irods-icat-4.0.3-64bit-centos6.rpm
        # ftp://ftp.renci.org/pub/irods/releases/4.0.3-with-v1.4-database-plugins/irods-database-plugin-postgres-1.4-centos6.rpm
