---
- hosts: all
  sudo: true
  vars:
      document_root: /vagrant
      irods_root: /var/lib/irods/iRODS
      b2safe_root: "{{ irods_root }}/modules/b2safe"
      b2safe_git_url: https://github.com/EUDAT-B2SAFE/B2SAFE-core.git
      b2safe_git_version: release-3.0
  #pre_tasks:
  #    - name: Update all yum packages
  #      yum: name=* state=latest
  pre_tasks:
      - name: Get some required yum packages
        yum: name=git state=present
  roles:
      - irods-server
      - b2safe-module
