---
- hosts: all
  sudo: true
  vars:
      document_root: /vagrant
      irods_root: /var/lib/irods/iRODS
      irods_etc: /etc/irods
      irods_host: localhost
      irods_port: 1247
      b2safe_root: "{{ irods_root }}/modules/b2safe"
      b2safe_git_url: https://github.com/EUDAT-B2SAFE/B2SAFE-core.git
      b2safe_git_version: release-3.0
      epic_baseuri: http://epic4.storage.surfsara.nl/v2_B/handles
      rpm_dir: /vagrant/rpm
  vars_prompt:
      epic_user: "Enter the EPIC username"
      epic_prefix: "Enter the EPIC prefix"
      epic_pass: "Enter the EPIC password"
      epic_debug: "Run EPIC client in debug mode? (Write False or True)"
  #pre_tasks:
  #    - name: Update all yum packages
  #      yum: name=* state=latest
  pre_tasks:
      - name: Create directory for RPM files
        file: path={{ rpm_dir }} state=directory
      - name: Download EPEL RPM
        get_url:
            url=http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
            dest={{ rpm_dir }}/epel-release-6-8.noarch.rpm
      - name: Install EPEL RPM
        yum:
            name={{ rpm_dir }}/epel-release-6-8.noarch.rpm
            state=present
      - name: Get some required yum packages
        yum: name=git state=present
  roles:
      - irods-server
      - b2safe-module
