---
- hosts: all
  sudo: true
  vars:
      document_root: /vagrant
      irods_root: /var/lib/irods/iRODS
      irods_etc: /etc/irods
      irods_host: irods2
      irods_host_remote: irods1
      irods_zone: zone2
      irods_zone_remote: zone1
      irods_port: 1247
      irods_port_remote: 1247
      icat_host: localhost
      b2safe_root: "{{ irods_root }}/modules/b2safe"
      b2safe_git_url: https://github.com/BILS/B2SAFE-core.git
      b2safe_git_version: release-3.0
      epic_baseuri: http://epic4.storage.surfsara.nl/v2_B/handles
      rpm_dir: /vagrant/rpm
      python_bin: /usr/bin/python
  roles:
      - { role: pre, sudo: true }
      - { role: irods-server, sudo: true }
      - { role: b2safe-module, sudo: true }
      - { role: replication, sudo: false }
