---
# --------------------------------------------------------------------------------
# Additional tasks, for enabling the B2SAFE replication
# --------------------------------------------------------------------------------
- name: Add bils.re ruleset by Jani
  copy: src=bils.re dest={{ b2safe_root }}/rulebase
- name: Add EUDATUpdateParentPids.r to b2safe rules folder
  copy: src=EUDATUpdateParentPids.r dest={{ b2safe_root }}/rules
- name: Add acPostProcForDataObjRead rule in core.re
  replace:
      dest={{ irods_etc }}/core.re
      regexp='^acPostProcForDataObjRead\(\*ReadBuffer\)\ \{\ \}$'
      replace='acPostProcForDataObjRead(*ReadBuffer) {\n\tif (*cmd != "authZmanager.py") {\n\t\tEUDATAuthZ("$userNameClient#$rodsZoneClient", *cmd, *args, *response);\n\t}\n}'
      backup=yes
- name: Add crontab to run the shell script that runs the EUDATUpdateParentPids
        custom (workaround) rule
  lineinfile:
      dest=/etc/crontab
      state=present
      insertafter=EOF
      line='0,10,20,30,40,50 * * * * vagrant /vagrant/scripts/run_eudateupdateparentpids_rule.sh > /var/tmp/EUDATUpdateParentPids.log 2>&1'
