---
# For reference, see these slides: http://irods.org/wp-content/uploads/2012/08/irods-admin.pdf
# ... and also, this document on EUDAT: http://www.eudat.eu/User%20Documentation%20-%20MPI-PL-SARA-RZG%20iRODS%20Zone%20Federation.html
