---
  - name: Create directory for b2safe
    file: path={{ b2safe_root }} state=directory
  - name: Check out B2SAFE from github
    git: 
        repo={{ b2safe_git_url }}
        dest={{ b2safe_root }}
        version={{ b2safe_git_version }}
