---
  - name: Create directory for b2safe
    file: path=/opt/b2safe state=directory
  - name: Check out B2SAFE from github
    git: 
        repo=https://github.com/EUDAT-B2SAFE/B2SAFE-core.git
        dest=/opt/b2safe
        version=release-3.0
