#!/bin/bash

RESPFILE=$1
IRODSHOST=$2
IRODSPORT=$3
ZONENAME=$4

echo $IRODSHOST > $RESPFILE
echo $IRODSPORT >> $RESPFILE
echo "rods" >> $RESPFILE
echo $ZONENAME >> $RESPFILE
cat /tmp/irodspass >> $RESPFILE
